name: rele-zoo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.3.1
  - pytorch=1.10.2
  - tensorboardX
  - tensorboard
  - swig
  - pip:
      - pytest
      - mock
      - pytest-cov
      - pytest-benchmark
      - pytest-mypy
      - flake8
      - flake8-docstrings
      - mypy
      - ipython==7.26.0
      - click==8.0.1
      - box2d==2.3.10
      - box2d-py==2.3.8
      - box2d-kengz==2.3.3
      - gym==0.21.0
      - pyglet==1.5.21
      - moviepy==1.0.3
      - tqdm==4.62.3
      - hydra-core==1.1.1
      - ray[default]
      - prometheus_client==0.13.1
