name: rele-zoo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - tensorboardX
  - pip
  - pip:
      - pytest
      - mock
      - pytest-cov
      - pytest-benchmark
      - pytest-mypy
      - flake8
      - flake8-docstrings
      - mypy
      - gym
      - tqdm