name: rele-zoo
channels:
  - pytorch
  - rusty1s
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - tensorflow-gpu>=2.4.0
  - tensorboard
  - jupyter
  - jupyterlab
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pytest-benchmark
      - pytest-mypy
      - flake8
      - flake8-docstrings
      - mypy
      - gym