name: rele-zoo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - tensorboardX
  - tensorboard
  - pip
  - pip:
      - pytest
      - mock
      - pytest-cov
      - pytest-benchmark
      - pytest-mypy
      - flake8
      - flake8-docstrings
      - mypy
      - click==8.0.1
      - gym==0.21.0
      - pyglet==1.5.21
      - moviepy==1.0.3
      - tqdm==4.62.3