[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "relezoo"
authors = [{name = "Luis Ferro", email = "luisedof10@gmail.com"}]
dynamic = ["version", "description"]