_target_: relezoo.algorithms.reinforce.ReinforceContinuousPolicy
defaults:
  - network: simple-fc-mu-sigma
learning_rate: 1e-5
noise:
  name: ou-noise
  params:
    seed: 123
    size: "infer"
    mu: 0.0
    theta: 1.0
    sigma: 0.05