# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
max_batch_size: null
ax_config:
  max_trials: 10
  early_stop:
    minimize: false
    max_epochs_without_improvement: 10
    epsilon: 1.0e-05
  experiment:
    minimize: false
  client:
    verbose_logging: false
    random_seed: null
  is_noisy: true
  params:
    context.seed:
      type: choice
      value_type: int
      is_ordered: True
      values: [123, 456, 789]
    algorithm.policy.learning_rate:
      type: range
      value_type: float
      bounds: [1e-4, 1e-2]
    algorithm.batch_size:
      type: choice
      value_type: int
      is_ordered: True
      values: [2500, 5000, 7000]