defaults:
  - _self_
  - environments@env_train: cartpole
  - environments@env_test: cartpole
  - algorithm: reinforce-discrete
  - logger: tensorboard
  - override hydra/help: relezoo-help
  - override hydra/launcher: ray

##########################
## Experiment wise vars ##
##########################
context:
  experiment_name: Relezoo
  mode: train
  render: False
  eval_every: 1
  mean_reward_window: 100
  checkpoints: checkpoints/
  epochs: 50
  seed:
  gpu: True # use gpu if available

network:
  infer_in_shape: True
  infer_out_shape: True


##########################
### Runtime wise vars ####
##########################
ray:
  init:
    num_cpus: 4
    #4GB in bytes
    _memory: 4294967296
    dashboard_port: 8265
    ignore_reinit_error: True

hydra:
  run:
    dir: outputs/${context.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    dir: outputs/${context.experiment_name}/multirun
    subdir: ${hydra.job.num}/${now:%Y-%m-%d_%H-%M-%S}