defaults:
  - _self_
  - environments@env_train: cartpole
  - environments@env_test: cartpole
  - algorithm: reinforce-discrete
  - logger: tensorboard
  - override hydra/help: relezoo-help

##########################
## Experiment wise vars ##
##########################
context:
  experiment_name: Relezoo
  mode: train
  render: False
  eval_every: 10
  checkpoints: checkpoints/
  episodes: 50
  gpu: True # use gpu if available

network:
  infer_in_shape: True
  infer_out_shape: True


##########################
### Runtime wise vars ####
##########################
ray:
  cpus: 4
  #4GB in bytes
  memory: 4294967296
  dashboard_port: 8265

hydra:
  run:
    dir: outputs/${context.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    dir: outputs/${context.experiment_name}/multirun
    subdir: ${hydra.job.num}/${now:%Y-%m-%d_%H-%M-%S}