# This is a basic workflow to help you get started with Actions
name: ReleZoo - CI/CD pipeline
# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Run full test suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare CI/CD run
        uses: ./.github/actions/relezoo-ci-prepare

      - name: Run tests
        run: |
          xvfb-run -s "-screen 0 1400x900x24" pytest -v -s tests

  install-test:
    name: Install and test the tool works
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Install the tool
        uses: ./.github/actions/relezoo-ci-prepare

      - name: Run help commands
        run: |
          relezoo --help
          relezoo-run --help
        

#      - name: Generate badges
#       run: |
#          coverage=`coverage report | grep "TOTAL" | awk '{print $4}' | awk -F "%" '{print $1}'`
#
#          if (( $(echo "$coverage <= 50" | bc -l) )) ; then
#            COLOR=red
#          elif (( $(echo "$coverage > 80" | bc -l) )); then
#            COLOR=green
#          else
#            COLOR=orange
#          fi
#
#         curl "https://img.shields.io/badge/coverage-$coverage%25-$COLOR" > coverage.svg
          
