# This is a basic workflow to help you get started with Actions
name: ReleZoo - CI/CD pipeline
# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Run full test suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: ./environment.yaml
          activate-environment: rele-zoo

      - name: Setup additional dependencies
        run: |
          conda install pyopengl ffmpeg
          sudo apt update -y
          sudo apt install -y xvfb libglu1-mesa libglu1-mesa-dev

      - name: Run tests
        run: |
          xvfb-run -s "-screen 0 1400x900x24" pytest -v -s tests

#      - name: Generate badges
#       run: |
#          coverage=`coverage report | grep "TOTAL" | awk '{print $4}' | awk -F "%" '{print $1}'`
#
#          if (( $(echo "$coverage <= 50" | bc -l) )) ; then
#            COLOR=red
#          elif (( $(echo "$coverage > 80" | bc -l) )); then
#            COLOR=green
#          else
#            COLOR=orange
#          fi
#
#         curl "https://img.shields.io/badge/coverage-$coverage%25-$COLOR" > coverage.svg
          
