# This is a basic workflow to help you get started with Actions
name: ReleZoo - CI/CD pipeline
# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Run full test suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: ./environment.yaml
          activate-environment: rele-zoo

      - name: Setup os dependencies
        run: |
          conda install pyopengl
          apt install ffmpeg xvfb

      - name: Run tests
        run: |
          xvfb-run -s "-screen 0 1400x900x24" pytest -v -s tests
